
  - Time-stamp: <2013-12-22 12:07:17 vk>
  - Author:     Karl Voit, tools@Karl-Voit.at
  - License:    GPL v3
  - URL:        http://github.com/novoid/gettvthek


  *NOTE* 2013-12-22: with the latest changes of ORF TVThek, I was not
  able to fix this script. So: *this script here does not work any
  more!* I switched over to [[http://zdfmediathk.sourceforge.net/index.html][MediathekView]] which gets the job done and
  is maintained much better than my script.


  This script takes an URL from ORF-TVthek http://tvthek.orf.at/ and
  extracts a wmv file using streaming. This script was working at
  time-stamp above with Wheezy Debian GNU/Linux and mplayer version
  r34540. It might break in case of changes of ORF-TVthek.

  Depends on: cat, sed, grep, wget, mplayer (>= r34540)

  Usage:

  :  gettvthek.sh http://tvthek.orf.at/programs/1309553-Was-gibt-es-Neues-
                    ... normal invocation

  :  gettvthek.sh -d http://tvthek.orf.at/programs/1309553-Was-gibt-es-Neues-
                    ... activate debug mode

  :  gettvthek.sh -h 
                    ... show help


* Known Issues

- does not work with multi-episode streams like ZIB1
- implement URL-checking of $URL and print out error if it is not an TVthek URL
- 2013-12-21: does not work any more with the latest changes of
  TVThek :-(

